"""agregar credenciales meta a cuentas conectadas

Revision ID: 77b6b72a5e14
Revises: d75aaac8aaff
Create Date: 2026-08-24 09:14:16.812955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b6b72a5e14'
down_revision: Union[str, None] = 'd75aaac8aaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas_conectadas', sa.Column('id_externo', sa.String(length=60), nullable=False, server_default=''))
    op.add_column('cuentas_conectadas', sa.Column('access_token', sa.Text(), nullable=False, server_default=''))
    op.add_column('cuentas_conectadas', sa.Column('url_base_publica', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('cuentas_conectadas', sa.Column('token_actualizado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas_conectadas', 'token_actualizado_en')
    op.drop_column('cuentas_conectadas', 'url_base_publica')
    op.drop_column('cuentas_conectadas', 'access_token')
    op.drop_column('cuentas_conectadas', 'id_externo')
    # ### end Alembic commands ###
