"""esquema inicial

Revision ID: d75aaac8aaff
Revises: 
Create Date: 2026-08-20 08:18:58.227694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75aaac8aaff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprendizajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nivel_confianza', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_conectadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=40), nullable=False),
    sa.Column('nombre_cuenta', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado_conexion', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identidad_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=120), nullable=False),
    sa.Column('actividad', sa.String(length=255), nullable=False),
    sa.Column('zona', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('modo_operacion', sa.String(length=20), nullable=False),
    sa.Column('color_primario', sa.String(length=20), nullable=False),
    sa.Column('color_acento', sa.String(length=20), nullable=False),
    sa.Column('identidad_visual_definitiva', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('explicacion', sa.Text(), nullable=False),
    sa.Column('datos_utilizados', sa.Text(), nullable=False),
    sa.Column('nivel_confianza', sa.String(length=20), nullable=False),
    sa.Column('accion_recomendada', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herramienta', sa.String(length=120), nullable=False),
    sa.Column('datos_utilizados', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('requirio_aprobacion', sa.Boolean(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguidores_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('origen_datos', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campanias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('objetivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultados_resumen', sa.Text(), nullable=False),
    sa.Column('origen_oportunidad_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['origen_oportunidad_id'], ['oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formato', sa.String(length=40), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('pilar', sa.String(length=60), nullable=False),
    sa.Column('objetivo', sa.String(length=80), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('origen_datos', sa.String(length=20), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('titular', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=False),
    sa.Column('cta', sa.String(length=120), nullable=False),
    sa.Column('plantilla', sa.String(length=60), nullable=False),
    sa.Column('archivo_generado', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_medicion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alcance', sa.Integer(), nullable=False),
    sa.Column('visualizaciones', sa.Integer(), nullable=False),
    sa.Column('interacciones', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.Integer(), nullable=False),
    sa.Column('compartidos', sa.Integer(), nullable=False),
    sa.Column('guardados', sa.Integer(), nullable=False),
    sa.Column('clics', sa.Integer(), nullable=False),
    sa.Column('consultas', sa.Integer(), nullable=False),
    sa.Column('origen_datos', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_publicacion')
    op.drop_table('flyers')
    op.drop_table('publicaciones')
    op.drop_table('precios')
    op.drop_table('campanias')
    op.drop_table('usuarios')
    op.drop_table('servicios')
    op.drop_table('seguidores_historico')
    op.drop_table('registro_acciones')
    op.drop_table('oportunidades')
    op.drop_table('identidad_negocio')
    op.drop_table('decisiones')
    op.drop_table('cuentas_conectadas')
    op.drop_table('aprendizajes')
    # ### end Alembic commands ###
